### ISSUE TITLE
us-mn will need updating! (May 11 2024)

### ISSUE THREAD

**Issue by TheTaraStark** [kreativekorp/vexillo#13]
Unless the legislature moves heaven and earth at the last moment (and there's no indication they plan to do so), the Minnesota flag will be changing as of May 11 2024!

https://commons.wikimedia.org/wiki/File:Flag_of_Minnesota_(2023_redesign).svg
https://en.wikipedia.org/wiki/Flag_of_Minnesota#2024_flag

**Comment by RebeccaRGB** [comment]
https://www.kreativekorp.com/app/vexillo/?d=us-mn&t=properties
