### ISSUE TITLE
Roman Empire Flag

### ISSUE THREAD

**Issue by cristian-5** [kreativekorp/vexillo#2]
Hello, I would like to suggest a new flag: the Roman Empire flag.
It is nowadays used mostly for indicating the latin language (see duolingo and other language learning platforms), however it is still present in Rome, engraved (literally) everywhere.
For historical purposes but mainly to identify those who study Latin, Ecclesiastical Latin and Modern Latin (Neo Latin).

![](https://upload.wikimedia.org/wikipedia/commons/7/76/Romeinse_vlag.jpg)

Since some hate groups took the eagle as their symbol during WW2 now the flag only portrays a red background with a laurel crown in gold, with at its centre the abbreviation `S.P.Q.R` (Senātus PopulusQue Rōmānus, Popular Rome Senate).

# Important

The flag is rectangular, landscape and not portrait (the picture is a coat of arms so it appears in portrait but it isn't) and it the proportions can be taken directly from the Italian flag.

## References:
https://en.wikipedia.org/wiki/SPQR

**Comment by RebeccaRGB** [comment]
This is done, so closing this.
