### ISSUE TITLE
Toki Pona flag

### ISSUE THREAD

**Issue by pandaqwanda** [kreativekorp/vexillo#3]
add the toki pona flag
![image](https://user-images.githubusercontent.com/116114960/196762557-7d7d1903-9a7e-4b85-8958-1e6fc0c2c40b.png)

**Comment by RebeccaRGB** [comment]
As far as I know, there have been many (many) designs proposed for a toki pona flag, but the toki pona community as a whole has not adopted any particular design. Wikimedia Commons has a version with the toki pona logogram on a light blue field, but it does not appear to be used anywhere other than category pages.
