### ISSUE TITLE
Flag generation

### ISSUE THREAD

**Issue by TheTaraStark** [kreativekorp/vexillo#4]
What part of the code automatically generates the different styles of emoji from one base flag image? Or have you been generating these all manually? Is there an external program you use to generate them? Curious to know, could make "add this flag" requests a lot simpler in the future, folks could create their own forks, etc. Thanks!

**Comment by RebeccaRGB** [comment]
For emoji specifically, start here:
https://github.com/kreativekorp/vexillo/blob/master/main/java/Vexillo/src/com/kreative/vexillo/main/VexMoji.java

It is called from this script:
https://github.com/kreativekorp/vexillo/blob/master/flags/makefonts

For adding flags, you don't need to mess with the code, just add them to this directory:
https://github.com/kreativekorp/vexillo/tree/master/flags/flags

**Comment by mentalstring** [comment]
I've started using the country flags and I'm getting reports of some issues with it, e.g., outdated ones (Martinique&Mauritania), color issues (Russia's flag colors seem to be from the 1991-1993 version), and there may be more soon as more people spot them.

I'm wondering what would be the best way to report/address these to avoid doing them piecemeal and with it, generate multiple revisions with all flags being generated again in each.

I'm able to trigger the build of the flags, and for simple color issues, I can try submit PRs if it helps. But for new flag designs, I'm afraid I don't have the design chops.

@RebeccaRGB What would you prefer? Should I open an issue with all the things I find? Or, would you prefer an issue per each flag in case someone else wants to have a go at it?

And by the way, thank you for all the great work done with this!

**Comment by RebeccaRGB** [comment]
Yes, please open issues for all the, well, issues you find. One per flag would be nice for tracking purposes.

**Comment by RebeccaRGB** [comment]
Russia, Martinique, and Mauritania, since they've been identified as having issues above, have been fixed, so I'm closing this.
