### ISSUE TITLE
Western Sahara flag is flipped horizontally

### ISSUE THREAD

**Issue by mentalstring** [kreativekorp/vexillo#6]
Not sure if I'm missing something, but [it appears](https://en.wikipedia.org/wiki/Flag_of_Western_Sahara) that the Western Sahara flag is flipped horizontally?

**Comment by RebeccaRGB** [comment]
It's flipped horizontally because the flag is sinister-hoisted, or mounted to the left of the flagpole instead of to the right like most flags. It appears that all emoji fonts as well as Wikipedia flip it the other way, though, so I might as well change it to match.

**Comment by mentalstring** [comment]
Ah, I see — flags clearly aren't my speciality. Up to you whether to change it — I just wanted to report it in case something was amiss.

**Comment by RebeccaRGB** [comment]
Flag has been flipped to reflect (pun intended) Wikipedia and emoji fonts.

**Comment by mentalstring** [comment]
Thank you @RebeccaRGB!
