### ISSUE TITLE
Guadeloupe flag choice may have political connotation

### ISSUE THREAD

**Issue by mentalstring** [kreativekorp/vexillo#7]
It seems unavoidable that flags come with political connotations which isn't always the fun part — sorry about that, I'm only the messenger here.

Guadeloupe's official flag is the French one; from my understanding, Kreative Vexillo doesn't stick to just official one but sometimes whichever is most commonly used (which seems to be a good compromise).

Now, [from Wikipedia](https://en.wikipedia.org/wiki/Flag_of_Guadeloupe), it seems that Guadeloupe has not just a _regional flag_, but also a _locally used unofficial flag_ which is what [most emoji sets](https://emojipedia.org/flag-guadeloupe/) seems to be following (actually, its black variant from what I understand).

With this, Kreative Vexillo isn't using neither of those, but one proposed by an independentist party (movement?), sometimes used in demonstrations. Since there's a less politically charged one that also appears to be more widely used, perhaps that's the more straight forward path to address this?

**Comment by RebeccaRGB** [comment]
The black local variant is now the default.

**Comment by mentalstring** [comment]
Thank you @RebeccaRGB!
